### ISSUE TITLE
"go mod download" fails with invalid version for github.com/openfaasltd/actuated/types@v0.0.0-20240729175505-d862db002103

### ISSUE THREAD

**Issue by kastl-ars** [self-actuated/actuated-cli#8]
Hi,

I am trying to package the CLI for openSUSE. As the build is done offline, I need to vendor the go dependencies beforehand.

Unfortunately this fails:

```
$ go mod download
go: github.com/openfaasltd/actuated/types@v0.0.0-20240729175505-d862db002103: invalid version: git ls-remote -q origin in /home/XXX/go/pkg/mod/cache/vcs/5f40a7bb6a95c215c49d936867cb6eee519cad81bc94c572659cbf17e180d44c: exit status 128:
        fatal: could not read Username for 'https://github.com': terminal prompts disabled
$
```

Could you check what is wrong there?

Kind Regards,
Johannes

**Comment by alexellis** [comment]
What's wrong with using the binary?

**Comment by kastl-ars** [comment]
> What's wrong with using the binary?

Hi Alex,

thanks for the fast fix.

I prefer to only have one command to update what is on my machine, hence using packages from my linux distribution is the preferred way. Of course YMMV and there are more ways to do things...

Kind Regards,
Johannes

**Comment by alexellis** [comment]
You can include the binary inside your OpenSUSE package, this is a fairly normal option for distros, including rpm modules. There's no benefit of building from source.
